apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-service
        image: backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /data/logs
          name: backend-logs
        livenessProbe:
          httpGet:
            path: /isAlive
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /isReady
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
      volumes:
      - name: backend-logs
        persistentVolumeClaim:
          claimName: pvc-backend
      initContainers:
      - name: check-data
        image: busybox:latest
        command: ['sh', '-c', 'if [ -e /data/db ]; then cp -r /data/db /data/logs; echo "Data copied"; else echo "No data to copy"; fi']
        volumeMounts:
        - name: backend-logs
          mountPath: /data/logs
