apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: mongo:latest
            command:
            - sh
            - -c
            - mongodump --host mongodb-service-0.mongodb-service --db fiszki --out /backup/$(date +%Y-%m-%d_%H-%M-%S)
          restartPolicy: OnFailure
